# Generated by Django 4.1.1 on 2022-11-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_extensionusuario_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionusuario',
            name='web',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
