# Generated by Django 4.1.1 on 2022-10-16 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_libro_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
