# Generated by Django 4.1.1 on 2022-10-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_libro_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
