# Generated by Django 4.1.1 on 2022-10-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_libro_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_creacion',
            field=models.DateTimeField(verbose_name='%m/%d/%Y'),
        ),
    ]
