# Generated by Django 4.1.1 on 2022-10-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_libro_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='escritor',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
