# Generated by Django 4.1.1 on 2022-10-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_libro_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_creacion',
            field=models.DateTimeField(),
        ),
    ]
