# Generated by Django 4.1.1 on 2022-11-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_libro_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='creador',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
