# Generated by Django 4.1.1 on 2022-11-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_libro_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
