# Generated by Django 4.1.1 on 2022-11-08 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_libro_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='creador',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='libro',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
