# Generated by Django 4.1.1 on 2022-11-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_libro_creador_alter_libro_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='creador',
            field=models.CharField(max_length=100),
        ),
    ]
