# Generated by Django 4.1.1 on 2022-11-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_libro_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='creador',
            field=models.TextField(),
        ),
    ]
